// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	download "............/internal/satellite/tiles/download"
	azblob "....m/Azure/azure-storage-blob-go/azblob"
	mock "github.com/stretchr/testify/mock"
)

// DownloadImages is an autogenerated mock type for the DownloadImages type
type DownloadImages struct {
	mock.Mock
}

// GetDownloadJobs provides a mock function with given fields: metadata
func (_m *DownloadImages) GetDownloadJobs(metadata azblob.Metadata) *download.DJobs {
	ret := _m.Called(metadata)

	var r0 *download.DJobs
	if rf, ok := ret.Get(0).(func(azblob.Metadata) *download.DJobs); ok {
		r0 = rf(metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*download.DJobs)
		}
	}

	return r0
}

type mockConstructorTestingTNewDownloadImages interface {
	mock.TestingT
	Cleanup(func())
}

// NewDownloadImages creates a new instance of DownloadImages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDownloadImages(t mockConstructorTestingTNewDownloadImages) *DownloadImages {
	mock := &DownloadImages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
